### PR TITLE
Updated dates of publication 

### PR DESCRIPTION
**Pull request by FedericoCentoni**
Updated date of publication (Oct 2020) and date of last publication (Oct 2019).

### CODE REVIEW

**Comment by FedericoCentoni** [comment]
Could you please review these small code changes?
Thanks

**Review by Ryan-Harris93 — CHANGES_REQUESTED** [review]
I'm happy with the changes to the scripts and the inclusion of the new PHS templates. I noticed there is a cover-page-provisional word documents that still has the ISD logos, this isn't required anymore, can this be removed from the file list? Then I'm happy to approve.

**Review by Ryan-Harris93 — APPROVED** [review]

**Review by aghimi01 — APPROVED** [review]
Happy with the changes made to the publication date and last publication date. 
To note, this covers a 10 year period which is fine. Can merge.

**Review by aghimi01 — APPROVED** [review]
Changes to publication date, last published dates and SIMD 2020 looks good. Happy for these to be incorporated.

**Review by aghimi01 — COMMENTED** [review]
Looks fine Federico

**Review by aghimi01 — CHANGES_REQUESTED** [review]
Hi Federico,

I have reviewed the changes and the updates to current publication date, last publication and SIMD is fine.
I am not sure the PHS templates you uploaded are the right ones. I noticed the waiting times team released official statistics on cancelled planned operations 7th July. The templates used are for official statistics, same as we require for our publication. Please get in touch to ask for a copy - cover, summary and report which we could use. They also have footnotes which isn't in yours and it is important to capture as these with PHS details. Thanks

**Pull request merged**
